import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { detectLockfile, parsePackageLock, parseYarnLock, parsePnpmLock } from '../src/lockfile.js';

describe('Lockfile Detection & Parsing', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'manifestlock-lockfile-test-'));
  });

  afterEach(async () => {
    await fs.promises.rm(tmpDir, { recursive: true, force: true });
  });

  describe('detectLockfile', () => {
    it('detects package-lock.json when present', async () => {
      await fs.promises.writeFile(path.join(tmpDir, 'package-lock.json'), '{}');
      const detected = detectLockfile(tmpDir);
      expect(detected.type).toBe('package-lock.json');
      expect(detected.filePath).toBe(path.join(tmpDir, 'package-lock.json'));
    });

    it('detects yarn.lock when present', async () => {
      await fs.promises.writeFile(path.join(tmpDir, 'yarn.lock'), '# yarn lockfile v1\n');
      const detected = detectLockfile(tmpDir);
      expect(detected.type).toBe('yarn.lock');
      expect(detected.filePath).toBe(path.join(tmpDir, 'yarn.lock'));
    });

    it('detects pnpm-lock.yaml when present', async () => {
      await fs.promises.writeFile(path.join(tmpDir, 'pnpm-lock.yaml'), 'lockfileVersion: 5.4\n');
      const detected = detectLockfile(tmpDir);
      expect(detected.type).toBe('pnpm-lock.yaml');
      expect(detected.filePath).toBe(path.join(tmpDir, 'pnpm-lock.yaml'));
    });

    it('throws descriptive error if no lockfile is found', () => {
      expect(() => detectLockfile(tmpDir)).toThrowError(
        /No supported lockfile \(package-lock\.json, yarn\.lock, or pnpm-lock\.yaml\) found/,
      );
    });

    it('respects priority order: package-lock.json over yarn.lock', async () => {
      await fs.promises.writeFile(path.join(tmpDir, 'package-lock.json'), '{}');
      await fs.promises.writeFile(path.join(tmpDir, 'yarn.lock'), '# yarn lockfile\n');
      const detected = detectLockfile(tmpDir);
      expect(detected.type).toBe('package-lock.json');
    });
  });

  describe('parsePackageLock', () => {
    it('parses v2/v3 lockfile with packages map', () => {
      const lockfile = JSON.stringify({
        lockfileVersion: 3,
        packages: {
          '': { name: 'root-pkg', version: '1.0.0' },
          'node_modules/lodash': {
            version: '4.17.21',
            resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz',
          },
          'node_modules/@scope/pkg': {
            version: '1.2.3',
            resolved: 'https://registry.npmjs.org/@scope/pkg/-/pkg-1.2.3.tgz',
          },
        },
      });

      const parsed = parsePackageLock(lockfile);
      expect(parsed).toHaveLength(2);
      expect(parsed).toEqual(
        expect.arrayContaining([
          {
            name: 'lodash',
            version: '4.17.21',
            spec: 'lodash@4.17.21',
            tarballUrl: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz',
          },
          {
            name: '@scope/pkg',
            version: '1.2.3',
            spec: '@scope/pkg@1.2.3',
            tarballUrl: 'https://registry.npmjs.org/@scope/pkg/-/pkg-1.2.3.tgz',
          },
        ]),
      );
    });

    it('parses v1 lockfile with nested dependencies map', () => {
      const lockfile = JSON.stringify({
        lockfileVersion: 1,
        dependencies: {
          debug: {
            version: '4.3.4',
            resolved: 'https://registry.npmjs.org/debug/-/debug-4.3.4.tgz',
            dependencies: {
              ms: {
                version: '2.1.2',
                resolved: 'https://registry.npmjs.org/ms/-/ms-2.1.2.tgz',
              },
            },
          },
        },
      });

      const parsed = parsePackageLock(lockfile);
      expect(parsed).toHaveLength(2);
      expect(parsed).toEqual(
        expect.arrayContaining([
          expect.objectContaining({ name: 'debug', version: '4.3.4' }),
          expect.objectContaining({ name: 'ms', version: '2.1.2' }),
        ]),
      );
    });
  });

  describe('parseYarnLock', () => {
    it('parses classic yarn.lock v1 format', () => {
      const yarnLock = `
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY.
# yarn lockfile v1

"chalk@^4.1.0", "chalk@^4.1.2":
  version "4.1.2"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-4.1.2.tgz#aac0e2fd300ab73e8fa795c82557b897339822ff"
  integrity sha512-oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VAU72KsQUJkDYBC5z2KQ37ur0w95gUO636YTg==
  dependencies:
    ansi-styles "^4.1.0"
    supports-color "^7.1.0"

"@types/node@*":
  version "20.10.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.10.0.tgz#..."
`;

      const parsed = parseYarnLock(yarnLock);
      expect(parsed).toHaveLength(2);
      expect(parsed).toEqual(
        expect.arrayContaining([
          expect.objectContaining({
            name: 'chalk',
            version: '4.1.2',
            spec: 'chalk@4.1.2',
          }),
          expect.objectContaining({
            name: '@types/node',
            version: '20.10.0',
            spec: '@types/node@20.10.0',
          }),
        ]),
      );
    });
  });

  describe('parsePnpmLock', () => {
    it('parses pnpm-lock.yaml format with packages section', () => {
      const pnpmLock = `
lockfileVersion: 5.4

specifiers:
  lodash: ^4.17.21
  '@types/node': ^20.0.0

dependencies:
  lodash: 4.17.21

packages:
  '/lodash@4.17.21':
    resolution: {integrity: sha512-v2kMOQZ134...}
    dev: false

  '/@types/node@20.11.0':
    resolution: {integrity: sha512-abc...}
    dev: true

  '/pkg-with-peer@1.0.0(react@18.2.0)':
    resolution: {integrity: sha512-xyz...}
`;

      const parsed = parsePnpmLock(pnpmLock);
      expect(parsed).toHaveLength(3);
      expect(parsed).toEqual(
        expect.arrayContaining([
          expect.objectContaining({
            name: 'lodash',
            version: '4.17.21',
            spec: 'lodash@4.17.21',
          }),
          expect.objectContaining({
            name: '@types/node',
            version: '20.11.0',
            spec: '@types/node@20.11.0',
          }),
          expect.objectContaining({
            name: 'pkg-with-peer',
            version: '1.0.0',
            spec: 'pkg-with-peer@1.0.0',
          }),
        ]),
      );
    });
  });
});
